#!/usr/bin/env python3
"""
USENIX Security 2027 Anonymous Artifact Packager for EviAssure.

Packages repository artifacts into a clean, metadata-stripped archive
`eviassure_usenix27_artifact.zip` for double-blind peer review.
"""

import sys
import os
import zipfile
import hashlib
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
OUTPUT_ZIP = REPO_ROOT / "eviassure_usenix27_artifact.zip"

INCLUDED_PATHS = [
    "assurance",
    "governance",
    "corpus",
    "specimens",
    "scripts",
    "tests",
    "README.md",
    "REPRODUCE.md",
    "pyproject.toml",
    "Makefile"
]

EXCLUDED_EXTS = {".pyc", ".DS_Store", ".pdf", ".png"}
EXCLUDED_DIRS = {"__pycache__", ".pytest_cache", ".git", ".paperloop"}


def create_anonymous_archive():
    print("=== USENIX Security 2027 Anonymous Artifact Packager ===")
    
    if OUTPUT_ZIP.exists():
        OUTPUT_ZIP.unlink()
        
    with zipfile.ZipFile(OUTPUT_ZIP, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for rel_path in INCLUDED_PATHS:
            abs_path = REPO_ROOT / rel_path
            if not abs_path.exists():
                print(f"[!] Warning: Path {rel_path} does not exist. Skipping.")
                continue
                
            if abs_path.is_file():
                arcname = os.path.join("eviassure_artifact", rel_path)
                zipf.write(abs_path, arcname)
                print(f" [+] Added file: {rel_path}")
            elif abs_path.is_dir():
                for root, dirs, files in os.walk(abs_path):
                    # Filter subdirectories
                    dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS]
                    for f in files:
                        ext = os.path.splitext(f)[1]
                        if ext in EXCLUDED_EXTS:
                            continue
                        full_f = Path(root) / f
                        rel_f = full_f.relative_to(REPO_ROOT)
                        arcname = os.path.join("eviassure_artifact", str(rel_f))
                        zipf.write(full_f, arcname)
                        print(f" [+] Added file: {rel_f}")
                        
    # Compute SHA-256 digest of artifact
    hasher = hashlib.sha256()
    with open(OUTPUT_ZIP, 'rb') as f:
        while chunk := f.read(65536):
            hasher.update(chunk)
            
    digest = hasher.hexdigest()
    size_kb = OUTPUT_ZIP.stat().st_size / 1024.0
    print(f"\n[SUCCESS] Anonymous review artifact created: {OUTPUT_ZIP.name}")
    print(f"          Size: {size_kb:.2f} KB")
    print(f"          SHA-256 Digest: {digest}")
    
    # Save digest file for LaTeX referencing
    digest_file = REPO_ROOT / "docs" / "artifact_digest.tex"
    digest_file.write_text(
        f"% GENERATED by scripts/prepare_anonymous_artifact.py\n"
        f"\\newcommand{{\\artifactShaDigest}}{{{digest[:16]}...}}\n"
        f"\\newcommand{{\\artifactSizeKb}}{{{size_kb:.1f}}}\n"
    )
    return digest


if __name__ == "__main__":
    create_anonymous_archive()
